#!/usr/bin/env bash
# install nginx and adjust default homepage
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html
sudo nginx -t

sudo service nginx reload
