#!/usr/bin/env bash
# a script that displays the PID, along with the process name,
# of processes whose name contain the word bash.

pids="$(pgrep -f bash)"
for pid in $pids
do
	name="$(ps -p "$pid" -o comm=)"
	echo "$pid $name"
done

